### ISSUE TITLE
start failure

### ISSUE THREAD

**Issue by eugenetaranov** [lebinh/aq#8]
Hello,

aq currently fails on importing prompt-toolkit, could you please advise what version of prompt-toolkit is known to work?
pip freeze:
`aq==0.1.1
asn1crypto==0.24.0
boto3==1.9.130
botocore==1.12.130
cryptography==2.1.4
docopt==0.6.2
docutils==0.14
enum34==1.1.6
futures==3.2.0
idna==2.6
ipaddress==1.0.17
jmespath==0.9.4
keyring==10.6.0
keyrings.alt==3.0
prompt-toolkit==2.0.9
pycrypto==2.6.1
Pygments==2.3.1
pygobject==3.26.1
pyparsing==2.4.0
python-dateutil==2.8.0
pyxdg==0.25
s3transfer==0.2.0
SecretStorage==2.3.1
six==1.11.0
tabulate==0.8.3
urllib3==1.24.1
wcwidth==0.1.7`

**Comment by mtoftum** [comment]
I'm pretty sure it broke once it got past 2.x - try grabbing one of the later versions in 1.x. 
The changes in prompt-toolkit broke just about everywhere else it was in use with the move to 2.x

**Comment by crsuarez** [comment]
> I'm pretty sure it broke once it got past 2.x - try grabbing one of the later versions in 1.x.
> The changes in prompt-toolkit broke just about everywhere else it was in use with the move to 2.x

Is not broke, prompt_toolkit now works with asyncio. https://github.com/prompt-toolkit/python-prompt-toolkit/blob/master/CHANGELOG#L341

**Comment by mtoftum** [comment]
I'll rephrase in case it wasn't obvious. aq is compatible with prompt-toolkit 1.something,  it does not work with prompt-toolkit >= 2

**Comment by psa-jforestier** [comment]
I fix this startup error with pip-downgrading some library with  : 
`pip3 install ipython==6.5.0 ptpython==0.41
`
After starting, aq failed with a Python error "AttributeError", as reported in #7 .

It will be great if we could have a working Docker container with all dependencies in correct version to make aq works.

**Comment by john-aws** [comment]
For me, the failing symptoms are:

```
me:~$ aq
Traceback (most recent call last):
  File "/Users/me/.pyenv/versions/3.7.9/bin/aq", line 5, in <module>
    from aq import main
  File "/Users/me/.pyenv/versions/3.7.9/lib/python3.7/site-packages/aq/__init__.py", line 29, in <module>
    from aq.prompt import AqPrompt
  File "/Users/me/.pyenv/versions/3.7.9/lib/python3.7/site-packages/aq/prompt.py", line 6, in <module>
    from prompt_toolkit import AbortAction, CommandLineInterface
ImportError: cannot import name 'AbortAction' from 'prompt_toolkit' (/Users/me/.pyenv/versions/3.7.9/lib/python3.7/site-packages/prompt_toolkit/__init__.py)
```

**Comment by mtoftum** [comment]
Be aware that this project is abandon-ware. Last commit is almost 5 years ago.

@john-aws most likely you have installed prompt-toolkit 2.x or 3.x - aq is only compatible with older 1.x versions of prompt-toolkit.

**Comment by john-aws** [comment]
@mtoftum thanks, I missed that.
